---
- name: Update apt cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - acl
      - python3-pymsql
      - mysql-client
      - pip
    state: present

- name: Install amazon.aws.aws_ssm prerequisities
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    state: present

- name: Create users
  ansible.builtin.user:
    name: "{{ item }}"
    create_home: true
    state: present
    shell: /bin/bash
    password: "!"
  with_items:
    - "{{ app_user }}"

- name: Ensure .ssh directories for users
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh/"
    state: directory
    mode: 0700
    owner: "{{ item }}"
    group: "{{ item }}"
